version:  '3'
services:
  backend-app:
    build: ./datacenter/.
    ports:
      - "5000:8080"
    restart: "no"
  frontend-app:
    build: ./dehing_patkai/.
    ports:
      - "5001:3000"
    restart: "no"